name: Auto-Renew Cron Job

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  auto-renew:
    runs-on: ubuntu-latest
    steps:
      - name: Run Auto-Renew
        run: |
          curl -X GET https://web-production-4bee0.up.railway.app/api/cron/auto-renew \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
